### PR TITLE
Made UI cleaner

### LINKED ISSUE #6: Make UI better

### PR DESCRIPTION
**Pull request by Virtual4087**
Fixes #6 

Screenshot:
Before:
image

After:
image

### CODE REVIEW

**Comment by Adarsh-Saurabh** [comment]
Can you improve the color scheme of the whole page?
It looks very simple and boring.
You can improve upon the buttons that are stone, paper, and scissors.

Also, comment under the issue I will assign this task to you!

**Comment by Virtual4087** [comment]
Ok I'll do that and I've already commented below the issue so you can assign it to me

**Comment by Adarsh-Saurabh** [comment]
yes done

**Comment by Adarsh-Saurabh** [comment]
Assigned!

**Pull request closed without merging**
