### PR TITLE
fixed input validation and redirection

### LINKED ISSUE #7: When clicking on the submit button without choosing the move. Website shows the bad request error

### PR DESCRIPTION
**Pull request by vens8**
Fixes #7 
The site doesn't give "bad request" when the submit button is clicked without selecting a radio button. Will work on the UI and add other features as well soon enough. Kindly approve this.

### CODE REVIEW

**Comment by vens8** [comment]
Also fixed the flask structure

**Review by Adarsh-Saurabh — APPROVED** [review]
Ok looks good

**Comment by Adarsh-Saurabh** [comment]
After I merged your pull request there's unusual behaviour in the website.
1. when I start the game it gives me more than one point some times 2 or 3.
2. The whole page is blinking just after submitting check this issue also.

**Comment by vens8** [comment]
Oh that's weird, didn't notice anything as such personally. Please add this as a new issue and i'll comment so you can assign me. I'll work on it immediately.

**Comment by Adarsh-Saurabh** [comment]
https://stone-paper-scissor-game.onrender.com/
check here

**Comment by Adarsh-Saurabh** [comment]
Go check

**Pull request merged**
